[package]
name = "proxy"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
app = { path = "../app" }

anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
bytes = "1.7"
bitcoin = { version = "0.32", features = ["std"] }
